version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '5175:5173'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
